### ISSUE TITLE
Document how this is better than https://github.com/mark-hahn/comment-down

### ISSUE THREAD

**Issue by bean5** [evmorov/next-line-comment#1]

**Comment by mark-hahn** [comment]
It is pretty obvious this maintains the current cursor position.  If there is another difference someone let me know.

I'll try this out for a while and if I'm happy I'll remove `comment-down` and steer people to this.  I am always happy to have less to support.  (grin)

**Comment by evmorov** [comment]
@bean5 , this package isn’t better, it’s just a bit different. You are right that from the perspective of an end-user it looks quite the same. I’ll update the description. However as @mark-hahn  mentioned this package saves the cursor position.

To be honest now I’m not sure that I was right that I created this package. I use JetBrain’s IDE at work and I looked for the same commenting behaviour. Mark’s package moves the cursor to the beginning. I wanted to make this feature optional with PR but then I realised that a cursor doesn’t save a position. This behaviour was really annoying and It can’t be fixed easily (the package should be reimplemented). So this package was created. After several days I noticed that JetBrain’s IDE doesn’t save a cursor position so I was a bit wrong.

These two packages are trying to solve the same problem but internally they are not the same. However Mark’s package is simpler and more robust, it doesn't save a position of a cursor. I think they can live together for now.

**Comment by bean5** [comment]
Cool. Glad you guys are communicating. I did see that they seemed to be similar and I couldn't tell what actual differences existed (based on just descriptions provided in Atom). I don't like it when people make projects that don't need to exist since it makes it harder to choose packages as a user. But perhaps in this case you just both tackled a legitimate need concurrently. Not much harm in having both, but clarification upfront on what each does would be good. In any case, I wish you the best. Thanks for contributing.
