### ISSUE TITLE
Not working on my setup

### ISSUE THREAD

**Issue by mark-hahn** [evmorov/next-line-comment#2]
Enabling this package seems to have no effect on my setup.  Is there something that I need to do to enable it after installing?  Does it work on all platforms and file types?

My setup ..

coffeescript file
atom 1.5.3
ubuntu 14.04
apm  1.6.0
npm  2.13.3
node 0.10.40
python 2.7.3
git 1.7.9.5

**Comment by evmorov** [comment]
@mark-hahn I think I know where is the problem. I had the same issue on Windows but forgot to fix it. I'll look into this. Thanks!
